<p>Dear %SALUTATION% %FIRSTNAME% %SURNAME%,</p>
$Member.Email
<h1>$Title</h1>
$Content

<p>This message was send from %FROM% to %USER_EMAIL%...</p>

<i>This Newsletter is generated by 'NewsletterTemplate.ss', the default Newsletter template</i>

<p>Unsubscripe newsletter <a href="{$BaseHref}newsletter/unsubscribe/%USER_EMAIL%/%NEWSLETTER_ID%">here</a>.</p>